import { CivicMap } from "@/components/CivicMap";
import { CivicShell } from "@/components/CivicShell";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, Clock3, Filter, MapPinned, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";

type CountRow = [string, number];
const barColors: Record<string, string> = { LOW: "bg-emerald-500", MEDIUM: "bg-amber-500", HIGH: "bg-orange-500", CRITICAL: "bg-red-600", Submitted: "bg-slate-500", "Under Review": "bg-amber-500", Assigned: "bg-blue-500", "In Progress": "bg-orange-500", Resolved: "bg-emerald-600" };

function Distribution({ title, rows, caption }: { title: string; rows: CountRow[]; caption: string }) {
  const maximum = Math.max(...rows.map(([, count]) => count), 1);
  return <section className="rounded-2xl border border-[#e0e9e2] bg-white p-5 shadow-[0_7px_22px_rgba(21,62,53,.05)]"><div className="flex items-start justify-between gap-3"><div><h2 className="font-display text-xl font-semibold text-[#153e35]">{title}</h2><p className="mt-1 text-sm text-[#71837a]">{caption}</p></div><TrendingUp size={18} className="text-[#e66a40]" /></div><div className="mt-5 space-y-3">{rows.map(([label, count]) => <div key={label}><div className="mb-1.5 flex items-center justify-between text-xs font-semibold text-[#587067]"><span>{label}</span><span>{count}</span></div><div className="h-2 overflow-hidden rounded-full bg-[#edf3ee]"><div className={`h-full rounded-full ${barColors[label] ?? "bg-[#2f7655]"}`} style={{ width: `${Math.max((count / maximum) * 100, 5)}%` }} /></div></div>)}</div></section>;
}

export default function Analytics() {
  const dashboard = trpc.civic.dashboard.useQuery();
  const [category, setCategory] = useState("ALL"); const [severity, setSeverity] = useState("ALL"); const [status, setStatus] = useState("ALL"); const [department, setDepartment] = useState("ALL"); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const allReports = dashboard.data?.reports ?? [];
  const reports = useMemo(() => allReports.filter(report => { const created = report.createdAt.slice(0, 10); return (category === "ALL" || report.category === category) && (severity === "ALL" || report.severity === severity) && (status === "ALL" || report.status === status) && (department === "ALL" || report.department === department) && (!from || created >= from) && (!to || created <= to); }), [allReports, category, severity, status, department, from, to]);
  const options = (key: "category" | "department" | "status") => Array.from(new Set(allReports.map(report => report[key]))).sort();
  const countBy = (get: (report: typeof reports[number]) => string) => Object.entries(reports.reduce<Record<string, number>>((total, report) => { const key = get(report); total[key] = (total[key] ?? 0) + 1; return total; }, {})).sort((a, b) => b[1] - a[1]);
  const hotspots = useMemo(() => countBy(report => report.address.split(",").slice(-2).join(",").trim()).slice(0, 4), [reports]);
  const categoryRows = useMemo(() => countBy(report => report.category).slice(0, 5), [reports]);
  const severityRows = useMemo(() => countBy(report => report.severity), [reports]);
  const statusRows = useMemo(() => countBy(report => report.status), [reports]);
  const resolved = reports.filter(report => report.status === "Resolved");
  const resolutionRate = reports.length ? Math.round((resolved.length / reports.length) * 100) : 0;
  const timed = resolved.filter(report => report.resolvedAt);
  const averageResolutionDays = timed.length ? (timed.reduce((total, report) => total + (new Date(report.resolvedAt!).getTime() - new Date(report.createdAt).getTime()) / 86_400_000, 0) / timed.length).toFixed(1) : "—";
  const trend = useMemo(() => Object.entries(reports.reduce<Record<string, number>>((total, report) => { const date = new Date(report.createdAt).toLocaleDateString(undefined, { month: "short", day: "numeric" }); total[date] = (total[date] ?? 0) + 1; return total; }, {})).slice(-7), [reports]);
  const trendMax = Math.max(...trend.map(([, count]) => count), 1);
  return <CivicShell title="Civic issue heatmap" eyebrow="Map-based analytics"><section className="rounded-2xl border border-[#e0e9e2] bg-white p-4 shadow-[0_7px_22px_rgba(21,62,53,.05)]"><div className="flex items-center gap-2"><Filter size={17} className="text-[#e66a40]" /><p className="text-sm font-bold text-[#153e35]">Filter civic activity</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6"><Select value={category} onValueChange={setCategory}><SelectTrigger aria-label="Filter by category"><SelectValue placeholder="Category" /></SelectTrigger><SelectContent><SelectItem value="ALL">All categories</SelectItem>{options("category").map(option => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select><Select value={severity} onValueChange={setSeverity}><SelectTrigger aria-label="Filter by severity"><SelectValue placeholder="Severity" /></SelectTrigger><SelectContent><SelectItem value="ALL">All severities</SelectItem>{["LOW", "MEDIUM", "HIGH", "CRITICAL"].map(option => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger aria-label="Filter by status"><SelectValue placeholder="Status" /></SelectTrigger><SelectContent><SelectItem value="ALL">All statuses</SelectItem>{options("status").map(option => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select><Select value={department} onValueChange={setDepartment}><SelectTrigger aria-label="Filter by department"><SelectValue placeholder="Department" /></SelectTrigger><SelectContent><SelectItem value="ALL">All departments</SelectItem>{options("department").map(option => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select><Input type="date" aria-label="From date" value={from} onChange={event => setFrom(event.target.value)} /><Input type="date" aria-label="To date" value={to} onChange={event => setTo(event.target.value)} /></div></section>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Total reports", value: reports.length, icon: MapPinned, tone: "bg-white text-[#153e35]" }, { label: "Resolved reports", value: resolved.length, icon: CheckCircle2, tone: "bg-[#e9f7ed] text-[#1c7147]" }, { label: "Resolution rate", value: `${resolutionRate}%`, icon: TrendingUp, tone: "bg-[#edf4ff] text-[#285e9e]" }, { label: "Average resolution", value: `${averageResolutionDays} days`, icon: Clock3, tone: "bg-[#fff7e8] text-[#a96911]" }].map(metric => <div key={metric.label} className={`rounded-2xl p-5 shadow-[0_7px_22px_rgba(21,62,53,.05)] ${metric.tone}`}><metric.icon size={18} /><p className="mt-4 text-2xl font-semibold">{metric.value}</p><p className="mt-1 text-sm opacity-75">{metric.label}</p></div>)}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.22fr_.78fr]"><div className="overflow-hidden rounded-2xl border border-[#e0e9e2] bg-white p-4 shadow-[0_7px_22px_rgba(21,62,53,.05)]"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-display text-xl font-semibold text-[#153e35]">Geographic hotspots</h2><p className="mt-1 text-sm text-[#708178]">{reports.length} reports matching the selected filters</p></div><span className="inline-flex items-center gap-1 text-xs font-bold text-[#667b70]"><span className="h-2 w-2 rounded-full bg-red-600" />Critical <span className="ml-2 h-2 w-2 rounded-full bg-orange-600" />High</span></div><CivicMap markers={reports.map(report => ({ latitude: report.latitude, longitude: report.longitude, label: `${report.issueType} · ${report.status}`, severity: report.severity }))} className="h-[430px] rounded-xl" /></div><div className="space-y-5"><div className="rounded-2xl bg-[#fff3ed] p-5"><AlertTriangle className="text-[#e66a40]" /><p className="mt-4 text-2xl font-semibold text-[#aa4423]">{reports.filter(report => ["HIGH", "CRITICAL"].includes(report.severity)).length}</p><p className="mt-1 text-sm text-[#995c45]">High-risk reports in this view</p></div><section className="rounded-2xl border border-[#e0e9e2] bg-white p-5 shadow-[0_7px_22px_rgba(21,62,53,.05)]"><div className="flex items-center gap-2"><MapPinned size={17} className="text-[#e66a40]" /><h2 className="font-display text-xl font-semibold text-[#153e35]">Active hotspots</h2></div><div className="mt-4 space-y-4">{hotspots.map(([place, count], index) => <div key={place} className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#edf5ee] text-xs font-bold text-[#153e35]">{index + 1}</span><span className="text-sm font-medium text-[#3f594e]">{place}</span></div><Badge className="border-0 bg-[#f1f5f2] text-[#40594d]">{count} reports</Badge></div>)}{!hotspots.length && <p className="text-sm text-[#71837a]">No reports match the current filters.</p>}</div></section></div></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-3"><Distribution title="Issues by category" caption="Most frequent issue families" rows={categoryRows} /><Distribution title="Issues by severity" caption="Risk-level mix in the selected view" rows={severityRows} /><Distribution title="Issues by status" caption="Current progress across the resolution pipeline" rows={statusRows} /></section>
    <section className="mt-6 rounded-2xl bg-[#153e35] p-6 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#d8ff76]">Recent reporting trend</p><h2 className="mt-2 font-display text-2xl font-semibold">Daily report volume</h2><p className="mt-1 text-sm text-[#c1d3c8]">This view groups the seeded report timestamps by day and responds to the active filters.</p></div><Badge className="border border-white/15 bg-white/10 text-[#d8ff76]">{reports.length} total in view</Badge></div><div className="mt-7 grid h-36 grid-cols-7 items-end gap-3">{trend.map(([label, count]) => <div key={label} className="flex h-full flex-col justify-end"><div className="rounded-t-md bg-[#d8ff76]" style={{ height: `${Math.max((count / trendMax) * 100, 8)}%` }} title={`${label}: ${count} report${count === 1 ? "" : "s"}`} /><p className="mt-2 text-center text-[10px] text-[#b8cbc0]">{label}</p></div>)}{!trend.length && <p className="col-span-7 text-sm text-[#c1d3c8]">No reports match the selected filters.</p>}</div></section>
  </CivicShell>;
}
